### ISSUE TITLE
Bullet Damage Reduction

### ISSUE THREAD

**Issue by qdwag** [Brownie79/swade-macros-simple#10]
Hi Nnayl,

I've just realised something. The damage roll doesn't allow for any mods. For instance, I play in a modern setting where a lot of characters wear kevlar vests (-4 damage from bullets). 

There isn't a way for me to add a modifier when the damage is auto-rolled after the attack.

**Comment by Nnayl** [comment]
I take note.
Maybe i would insert a step between Attack and Damage. Some other settings need to be set at this moment.

**Comment by qdwag** [comment]
Thanks Nnayl. 
Yeah, an extra step will need to be inserted really otherwise there is no way to add damage mods. There are certain Powers as well that boost damage for a short period of time (maybe 1 turn +). And almost all Kevlar armour will have the standard -4 bullet damage. 

I really like the direction you’ve taken this script. I would love to be able to use this in my games as soon as damage mods are added. Well done again!

**Comment by Nnayl** [comment]
Damage modification is now available in v1.2.0
