### ISSUE TITLE
Request: Ignore Armor Damage

### ISSUE THREAD

**Issue by qdwag** [Brownie79/swade-macros-simple#11]
Hi Nnayl,

Thanks for doing those fantastic updates to your macro! 

One final request: are you able to add the "ignore armor" button that Spacemandev has in his macro? This allows for the situations where a Called-Shot is made to areas where there is no armor. Then armor needs to be ignored.

Thanks again.

**Comment by Nnayl** [comment]
Feature available in version 1.2.1.
- Add "ignore targey armor" setting in "Damage Settings" windows. Note : don't ignore armor from cover.
