### ISSUE TITLE
More control over ammo consumption

### ISSUE THREAD

**Issue by Yalnin** [Brownie79/swade-macros-simple#12]
My players quite often use "Double Tap" and Three-Round-Burst (M16 A2) which consume 2 or 3 ammo per shot respectively, but keeps the rate of fire of 1. Do you see a possibility to build this into the shooting macro? Thanks for your efforts.

**Comment by Nnayl** [comment]
Hi, i can will do. I found Three-Round-Burst rules (page 67), but not for Double Tap. Can you indicate me the page of rules ?

**Comment by Yalnin** [comment]
Double Tap is an edge, you find it on p. 41 in SWADE. Thanks!

**Comment by Nnayl** [comment]
Double Tap and Three Round Burst is available in v1.3.3
