### ISSUE TITLE
Combat Flow: Shaken on (damage > Toughness ) instead of (damage == Toughness)

### ISSUE THREAD

**Issue by dmpunks** [Brownie79/swade-macros-simple#25]
Hi,

![20200830_165221](https://user-images.githubusercontent.com/1963509/91662977-7bfad500-eb18-11ea-8e72-8bba233b77ec.jpg)
Combat Flow seems to be tagging damage rolls equal to Toughness + Armor as "No Damage" (please see attached screenshot).

**Comment by Nnayl** [comment]
Hi,

Bug fixed with 1.6.5.

Thanks for report !
