### ISSUE TITLE
SWADE Combat Flow: Armor piercing reducing base toughness when AP > Armor

### ISSUE THREAD

**Issue by Norc** [Brownie79/swade-macros-simple#26]
User Seth (the Invader Zim one) reported [this error](https://discordapp.com/channels/170995199584108546/715780900322803753/754138210401124362) with Combat Flow calculation in FVTT SWADE channel:

![image](https://user-images.githubusercontent.com/64667579/92987448-5f538b00-f490-11ea-999a-e7061752bd9d.png)

Looks to me like the Armor Piercing value is not properly capped at the Armor value, at least in this case.

**Comment by thadrine** [comment]
![savage error](https://user-images.githubusercontent.com/63060887/93002677-a41a0900-f506-11ea-9a9d-d90531f41310.png)
It gets even weirder. 
If you leave the AP field blank I got no damage (should have been Shaken and Raise result)
When I enterd 0AP it came out correct. 
This was testing it with regular combat flow.

**Comment by thadrine** [comment]
I have been messing with this a lot, and it really appears to be some sort of memory issue more than anything. 
I have not changed any mods, only experimenting with the different combat flows and the Toughness Autocalc. 
And I am getting different results each time, doing the same tests. 
![savage error](https://user-images.githubusercontent.com/63060887/93003037-42a76980-f509-11ea-8745-919a9d80f24c.png)

**Comment by thadrine** [comment]
I can repeat this issue on other fresh systems, and I can get different results while testing it the same aspect.

**Comment by Nnayl** [comment]
Hi,
 Bug fixed with 1.6.5

Thanks for report
