### ISSUE TITLE
SWADE Combat Flow macro looks to incorrectly factor in Shaken status of token for damage results of 1 Wound+

### ISSUE THREAD

**Issue by Norc** [Brownie79/swade-macros-simple#27]
User Skellan reported [this error](https://discordapp.com/channels/170995199584108546/715780900322803753/754030471913930773) with Combat Flow calculation in FVTT SWADE channel:

![image](https://user-images.githubusercontent.com/64667579/92987493-ddb02d00-f490-11ea-9798-2756cd99ccba.png)

Consulting with the table on Page 94 of the SWADE rulebook, the result should be 1 Wound and Remains shaken. this may only happen when the target is already shaken to start (this should not matter). The Shaken/Unshaken status of the token only matters when appling another Shaken result from Damage, not any damage result of a Wound or greater.

In any case, this particular calculation looks to be incorrect... I'm just speculating as to the underlying cause here.

**Comment by Nnayl** [comment]
Hi,

Bug fixed with 1.6.5.

Thanks for report
