### ISSUE TITLE
Re-roll Damage

### ISSUE THREAD

**Issue by qdwag** [Brownie79/swade-macros-simple#8]
**@Nnayl:** What happens when players want to reroll the damage dice (bennies)? Can you make a Re-roll damage button?

**Suggestion:**
What would be even better is a "Re-roll last attack", "Re-roll last damage" button in the chat. It remembers the last roll's mods so the players don't have to go through the whole process of adding mods again.

**Comment by Nnayl** [comment]
Reroll bennie is now available in v1.2.0, for attack and damage.
