### ISSUE TITLE
Localization Support

### ISSUE THREAD

**Issue by brunocalado** [Brownie79/swade-macros-simple#9]
Hi.

If possible, can you add localization support?

I can translate to my language (portuguese) and send to you.

Thank you.

**Comment by Nnayl** [comment]
It's on the todo list, english is not my native language too ! :)

I come back to you when the localization feature will be ready to use.

**Comment by Nnayl** [comment]
@brunocalado hi, the localization support is done. If you want, you can : 
- get the en.json file in lang folder
- translate it in your language
- send me file translated

and i will add it to the module

**Comment by Yalnin** [comment]
Hi Nnayl, I have made a German translation of the actual en.json, however I am new to GitHub... how can I send it to you?

**Comment by Nnayl** [comment]
@Yalnin can you share it to me here with a cloud link ?
I dont know if you can push it in Github directly, anyway i need to register it in module.json

**Comment by Nnayl** [comment]
@Yalnin version 1.4.4 released with German localization
Thanks you for you participation !

**Comment by brunocalado** [comment]
brazilian portuguese file

[pt-br.zip](https://github.com/Brownie79/swade-macros-simple/files/4891262/pt-br.zip)

**Comment by Nnayl** [comment]
@brunocalado it's missing some lines. I think you not have the lasted version.
missing lines from lasted version :  2 to 9, 47, 48

**Comment by brunocalado** [comment]
brazilian portuguese file


[por.zip](https://github.com/Brownie79/swade-macros-simple/files/4897338/por.zip)

**Comment by Nnayl** [comment]
Portugues localization is imported in last version.
